# Generated by Django 4.2.2 on 2023-08-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linker',
            name='pdb_id',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
