# Generated by Django 4.2.2 on 2023-08-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0002_alter_linker_pdb_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='flexibility',
            fields=[
                ('id', models.CharField(default='1', max_length=15, primary_key=True, serialize=False)),
                ('Sequence', models.CharField(max_length=100)),
                ('backbone', models.CharField()),
                ('average_flexibility', models.FloatField(default=0)),
                ('pdb_id', models.CharField(default='N/A', max_length=15)),
                ('type', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='linker',
            name='Reference',
            field=models.CharField(default='N/A', max_length=400),
        ),
    ]
