# Generated by Django 4.2.2 on 2023-08-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0004_hydrophobicity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexibility',
            name='pdb_id',
        ),
    ]
