# Generated by Django 4.2.2 on 2023-08-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0006_alter_flexibility_backbone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linker',
            name='Source',
            field=models.CharField(default='NA', max_length=350),
        ),
    ]
