# Generated by Django 4.2.2 on 2023-08-10 01:11

from django.db import migrations, models
import linkers_website.apps.test3.models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0007_alter_linker_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linker',
            name='id',
            field=models.CharField(default=linkers_website.apps.test3.models.Linker.generate_unique_6_digit_number, max_length=15, primary_key=True, serialize=False),
        ),
    ]
