# Generated by Django 4.2.2 on 2023-07-17 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linker',
            name='length',
        ),
    ]
