# Generated by Django 4.2.2 on 2023-07-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkers', '0002_remove_linker_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='linker',
            name='length',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
