# Generated by Django 4.2.2 on 2023-07-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkers', '0003_linker_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linker',
            name='type',
        ),
        migrations.AddField(
            model_name='linker',
            name='Origin',
            field=models.CharField(default='3', max_length=225),
        ),
        migrations.AddField(
            model_name='linker',
            name='region',
            field=models.CharField(default='2', max_length=20),
        ),
        migrations.AddField(
            model_name='linker',
            name='secondary_structure',
            field=models.CharField(default='HHHH', max_length=30),
        ),
        migrations.AlterField(
            model_name='linker',
            name='aasequence',
            field=models.CharField(default='HELLO', max_length=255),
        ),
        migrations.AlterField(
            model_name='linker',
            name='id',
            field=models.CharField(default='1', max_length=15, primary_key=True, serialize=False),
        ),
    ]
