# Generated by Django 4.2.2 on 2023-07-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkers', '0004_remove_linker_type_linker_origin_linker_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linker',
            name='length',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
