# Generated by Django 4.2.2 on 2023-07-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkers', '0005_alter_linker_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linker',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
