# Generated by Django 4.2.2 on 2023-07-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkers', '0006_alter_linker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linker',
            name='Origin',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='linker',
            name='aasequence',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='linker',
            name='length',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='linker',
            name='region',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='linker',
            name='secondary_structure',
            field=models.CharField(max_length=30),
        ),
    ]
