# Generated by Django 4.2.2 on 2023-07-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkers', '0008_alter_linker_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linker',
            name='length',
            field=models.IntegerField(max_length=50),
        ),
    ]
