# Generated by Django 4.2.2 on 2023-07-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkers', '0010_alter_linker_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linker',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='linker',
            name='secondary_structure',
            field=models.CharField(max_length=100),
        ),
    ]
