# Generated by Django 4.2.2 on 2023-07-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkers', '0012_testdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='testdata',
            new_name='flexibility',
        ),
    ]
