# Generated by Django 4.2.2 on 2023-07-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkers', '0013_rename_testdata_flexibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='empmodel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
    ]
