# Generated by Django 4.2.2 on 2023-07-28 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkers', '0014_empmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='empmodel',
        ),
    ]
