# Generated by Django 4.2.2 on 2023-08-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkers', '0016_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='length',
        ),
    ]
