# Generated by Django 4.2.2 on 2023-08-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkers', '0017_remove_test_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('aasequence', models.CharField(max_length=255)),
                ('Origin', models.CharField(max_length=225)),
            ],
        ),
    ]
