# Generated by Django 4.2.2 on 2023-08-04 21:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('linkers', '0018_yourmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourmodel',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
