# Generated by Django 4.2.2 on 2023-08-04 21:26

from django.db import migrations, models
import linkers_website.apps.linkers.models


class Migration(migrations.Migration):

    dependencies = [
        ('linkers', '0019_alter_yourmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourmodel',
            name='id',
            field=models.CharField(default=linkers_website.apps.linkers.models.YourModel.generate_unique_6_digit_number, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
