# Generated by Django 4.2.2 on 2023-08-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkers', '0020_alter_yourmodel_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
