# Generated by Django 4.2.2 on 2023-08-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkers', '0022_hydrophobicity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hydrophobicity',
        ),
    ]
