# Generated by Django 4.2.2 on 2023-08-16 19:32

from django.db import migrations, models
import linkers_website.apps.Linker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flexibility',
            fields=[
                ('id', models.CharField(default=linkers_website.apps.Linker.models.flexibility.generate_unique_6_digit_number, max_length=15, primary_key=True, serialize=False)),
                ('Sequence', models.CharField(max_length=100)),
                ('backbone', models.CharField(default='NA')),
                ('average_flexibility', models.FloatField(default=0)),
                ('type', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hydrophobicity',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('sequence', models.CharField(max_length=100)),
                ('acidic_very_hydrophobic', models.FloatField(default=0)),
                ('acidic_hydrophobic', models.FloatField(default=0)),
                ('acidic_neutral', models.FloatField(default=0)),
                ('acidic_hydrophilic', models.FloatField(default=0)),
                ('neutral_very_hydrophobic', models.FloatField(default=0)),
                ('neutral_hydrophobic', models.FloatField(default=0)),
                ('neutral_neutral', models.FloatField(default=0)),
                ('neutral_hydrophilic', models.FloatField(default=0)),
                ('gravy_score', models.FloatField(default=0)),
                ('acidic_img_data', models.TextField()),
                ('neutral_img_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Linker',
            fields=[
                ('id', models.CharField(default=linkers_website.apps.Linker.models.Linker.generate_unique_6_digit_number, max_length=15, primary_key=True, serialize=False)),
                ('pdb_id', models.CharField(default='N/A', max_length=15)),
                ('length', models.IntegerField(default=0)),
                ('aasequence', models.CharField(max_length=255)),
                ('Source', models.CharField(default='NA', max_length=350)),
                ('Reference', models.CharField(default='N/A', max_length=400)),
            ],
        ),
    ]
