# Generated by Django 4.2.2 on 2023-10-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linker',
            name='Source',
            field=models.CharField(default='N/A', max_length=350),
        ),
    ]
