# Generated by Django 4.2.2 on 2023-08-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlinker',
            name='id',
            field=models.CharField(default='1', max_length=15, primary_key=True, serialize=False),
        ),
    ]
