# Generated by Django 4.2.2 on 2023-07-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='backbone',
            field=models.JSONField(),
        ),
    ]
