# Generated by Django 4.2.2 on 2023-07-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0002_alter_testdata_backbone'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='average_flexibility',
            field=models.FloatField(default=0),
        ),
    ]
