# Generated by Django 4.2.2 on 2023-07-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0003_testdata_average_flexibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='backbone',
            field=models.CharField(),
        ),
    ]
